Fix MSVC build
Fixes:
```
FAILED: src/CMakeFiles/libakonadiconsole.dir/browserwidget.cpp.obj
...
Z:\CraftRoot\include\KF5\AkonadiCore/item.h(596): error C2039:
"auto_ptr" ist kein Member von "std".
```

This broke with dfae7770eac0658fab107e84a4fe9b92b38f0d36 where the required
CXX standard was raised to C++17. MSVC under C++17 no longer declares
std::auto_ptr by default.

See also:
  https://devblogs.microsoft.com/cppblog/c17-feature-removals-and-deprecations/
  (cite: "In C++17 mode, we remove features that were removed in the C++17 Standard (e.g. auto_ptr)")